package:
  name: sudo
  version: 1.9.16_p2
  epoch: 0
  description: Give certain users the ability to run some commands as root
  copyright:
    - license: ISC
  checks:
    disabled:
      - setuidgid
  dependencies:
    runtime:
      - merged-usrsbin
      - wolfi-baselayout

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - zlib-dev

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+(?:\.\d+(?:\.\d+)?)?)(_(p\d+))?$
    replace: "${1}${3}"
    to: mangled-package-version

pipeline:
  - uses: fetch
    with:
      expected-sha256: 976aa56d3e3b2a75593307864288addb748c9c136e25d95a9cc699aafa77239c
      uri: https://www.sudo.ws/dist/sudo-${{vars.mangled-package-version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --disable-nls \
        --enable-pie \
        --with-env-editor \
        --with-mdoc \
        --without-pam \
        --without-skey \
        --with-sendmail=/usr/bin/sendmail \
        --with-passprompt="[sudo] password for %p: " \
        --sbindir=/usr/bin

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

  - runs: |
      # sudo must be owned by root with setuid set
      chmod u+s ${{targets.contextdir}}/usr/bin/sudo
      chmod u+s ${{targets.contextdir}}/etc/sudo.conf
      chmod u+s ${{targets.contextdir}}/etc/sudoers

subpackages:
  - name: sudo-doc
    pipeline:
      - uses: split/manpages
    description: sudo manpages
    test:
      pipeline:
        - uses: test/docs
    dependencies:
      runtime:
        - merged-usrsbin
        - wolfi-baselayout

  - name: sudo-doc-extra
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/share/doc
          mv ${{targets.destdir}}/usr/share/doc/sudo ${{targets.contextdir}}/usr/share/doc/sudo
    description: sudo examples and news
    dependencies:
      runtime:
        - merged-usrsbin
        - wolfi-baselayout

  - name: sudo-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - merged-usrsbin
        - sudo
        - wolfi-baselayout
    description: sudo dev

test:
  environment:
    contents:
      packages:
        - shadow
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        # Add user
        useradd wolfi

        # Add user to sudoers file
        printf "\"%s\" ALL = (root) NOPASSWD:ALL\n" "wolfi" >> /etc/sudoers.d/sudoers

        # Set root password
        passwd << EOF
          password
          password
        EOF

        # We can't use login during tests so use sudo to run sudo as user
        sudo -u wolfi sudo -S whoami << EOF
          password
        EOF
        cvtsudoers --version
        cvtsudoers --help
        sudo --version
        sudo --help
        sudoedit --version
        sudoedit --help
        sudoreplay --version
        sudoreplay --help
        sudo_logsrvd --version
        sudo_logsrvd --help
        sudo_sendlog --version
        sudo_sendlog --help
        visudo --version
        visudo --help

update:
  enabled: true
  version-transform:
    - match: '_'
      replace: '.'
    - match: 'p'
      replace: '_p'
  release-monitor:
    identifier: 4906
